### PR TITLE
Changes and improvements to the layout

### PR DESCRIPTION
**Pull request by fingli**
I made some improvements by request of Philip Muller. 
1). Added "Archive" page - it is a list of all published articles. No human interaction needed, the new posts will be added automatically.
2). As an addition to the above -- added pagination to the front page. As it is now all posts appeared in the main page, this function divides them to separate pages. The number of post per page is adjustable from **_config.yml** `paginate: 4`
3). Fixed "Read more" link -- currently 'read more' is missing the parameter 'truncatewords'. It is adjustable from **index.html** `truncatewords: 60`
4). Cosmetic changes in the font settings for better legibility.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@teo: this feature is already tested on [our page](https://manjaro.github.io/). If needed, take a look.

**Comment by teo** [comment]
Can we truncate on a paragraph boundary instead of after a fixed number of words?

**Comment by fingli** [comment]
Yes. Here are some neat ideas http://briankhuu.com/blog/self/jekyll/2014/12/03/post-truncation-in-jekyll.html But I'm agree with the author that the better solution is to have an option manually add the excerpt wherever you like into the post, using `<!--more-->` tag or similar. In this way if for a reason you don't want to use excerpt of certain text, you can put at the end this tag.

I tweaked that code a little bit so the following appeared. First it searches for 'more' tag, if no, truncates at 60th word. In case you don't want to use automatically truncating, remove the %else% condition and you will use it only where it's set manually.
```
{% if post.content contains '<!--more-->' %}
    {{ post.content | split:'<!--more-->' | first }}
{% else %}
    {{ post.content | truncatewords: 60 }}
{% endif %}
```

**Comment by teo** [comment]
Thank you for the patch.

**Pull request merged**
