### PR TITLE
adding EndeavourOS welcome picture 

### PR DESCRIPTION
**Pull request by killajoe**
adding EndeavourOS welcome screenshot to gallery on index page.

### CODE REVIEW

**Comment by demmm** [comment]
Correct to remove that image, though 9 is not the only count allowed, one row is set to contain 9, so if there is interest/need, best to add one more row for a total of 18 (imo best to keep it limited to 2 images per distro, there just weren't 9 available so far)

**Comment by adriaandegroot** [comment]
I'm reading @demmm 's comment as "it is ok to drop one of the KaOS screenies". I wonder if maybe 2 rows -- if we gather enough screenies -- would be useful: one line of 9 welcome screens showing the diversity of distro's, and one line of 9 different view modules showing the range of features in Calamares. Something to think about later.

**Comment by demmm** [comment]
Agreed. Two lines of thumbnails would be better, especially with headers like `Welcome screens` & `Varied options`.  But it took a while to get shots from 7 different distros....., so might be a while before there are 2 shots from 9 distros.

**Comment by killajoe** [comment]
hmm image is to small

**Comment by killajoe** [comment]
> Agreed. Two lines of thumbnails would be better, especially with headers like `Welcome screens` & `Varied options`. But it took a while to get shots from 7 different distros....., so might be a while before there are 2 shots from 9 distros.

i can add some if requested ;)

**Pull request merged**
